### ISSUE TITLE
Declined transaction didn't leave transaction's history

### ISSUE THREAD

**Issue by Reveloper** [labraburn/juston-ios#17]
### Bug Type

Functional

### Reproduction steps

1. Click send transaction icon ↑ from the main screen of Juston.
2. Enter the correct address into the Address field and the available value into the Amount field.
3. Click Next.
4. Send a transaction into the blockchain from another TON wallet application and the same address(I've sent 0.13 TON).
5. Click Send in the Juston for approving the transaction.
6. Switch off the internet connection for a while (about ~30 sec).
7. Switch on the internet connection.
8. Check transaction history in the Juston.

### Actual result

Declined transaction displays in the transaction history and it will never disappear from there.

https://user-images.githubusercontent.com/39581753/191356521-8db9169f-6cee-44d3-bedd-7813ce4e59a4.mov

### Expected result

Refreshing transaction history and deleting the declined transactions from there. (i.e. Transactions, that were not sent in the blockchain)

### Suggested Severity

High

### Device

Smartphone
Device: iPhone12
OS: iOS 15.6.1
Juston 1.3.2

**Comment by oboupo** [comment]
Transaction history synchronised with blockchain and stored locally on device.

To refresh transaction history you should follow next steps:
-> tap 3 dots icon on wallet card
-> Tap re-synchronize menu item

This steps should fix this issue btw we can make it better.
